### ISSUE TITLE
The lack of Authentication

### ISSUE THREAD

**Issue by blueocean0724** [BlueOcean5911/shop_site#5]
This project does not have authentication like JWT or Google OAuth.

**Comment by plzbugmenot** [comment]
You can use template or libraries for this such as Larabel.
Thanks

**Comment by plzbugmenot** [comment]
![Capture](https://github.com/user-attachments/assets/9f7c4b62-b721-4db1-87c2-584c22aa6dad)
This could be help you to find method.

**Comment by blueocean0724** [comment]
Good suggestion.
But our backend is built-in fast-api. So we can use Authlib python library, but it has plan when our project is commercial. but I don't think that we care about it, because our project will be open source.
What do you think about it
