### ISSUE TITLE
Configuration for eslint

### ISSUE THREAD

**Issue by blueocean0724** [BlueOcean5911/shop_site#6]
We need to config our eslint because this is default. So config is not perfect for our purpose.

**Comment by plzbugmenot** [comment]
1. Use a .eslintrc Configuration File
Create a .eslintrc file in your project root to define your ESLint configuration. You can specify rules, environments, and parser options here.

2. Extend Popular Configurations
Consider extending popular ESLint configurations like eslint:recommended, airbnb, or prettier to inherit a set of best practices and formatting rules.
