### ISSUE TITLE
Consideration about Redux for storage management

### ISSUE THREAD

**Issue by blueocean0724** [BlueOcean5911/shop_site#7]
We are using light storage management currently, but we have to reconsider it carefully to mange the storage smoothly.

**Comment by plzbugmenot** [comment]
1. Use Redux Toolkit
Start with Redux Toolkit, which simplifies store setup and reduces boilerplate code. It includes utilities for creating slices, reducers, and actions.

npm install @reduxjs/toolkit react-redux
